nombre = input("Introduzca nombre del producto:")
precio = input("Introduzca el precio del producto:")
cantidad = input("Introduzca la cantidad de veces que coge el producto:")
descuento = input("Introduzca el porcentaje de descuento:")
print("Nombre del producto:", nombre,"Cantidad:", cantidad,"unidades. Descuento:",descuento,"%.")
print("Precio total sin descuento: ", float(precio)*int(cantidad),"€.")
print("Descuento aplicado:", descuento,"%.")
sin_descuento = float(precio)*int(cantidad)
dinero_descuentado = sin_descuento*(int(descuento)/100)
con_descuento = sin_descuento-dinero_descuentado
print("El precio final, una vez aplicado el descuento es de:", con_descuento,"€ ahorrando un total de:",dinero_descuentado,"€.")
print("Otra forma de escribir el precio final sin descuento:" + str(sin_descuento) + "€.")
print("Otra forma de escribir cuando dinero se ahorra:" + str(dinero_descuentado)+"€.")
print("Otra forma de escribir el precio final:" + str(con_descuento)+"€.")
